# Generated by Django 2.2.5 on 2019-09-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pab_date',
            new_name='pub_date',
        ),
    ]
